/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package capa_Presentacion;

import javax.swing.JOptionPane;

/**
 *
 * @author Sh
 */
public class frmMenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form frmMenuPrincipal
     */
    public frmMenuPrincipal() {
        initComponents();
        //this.setExtendedState(MAXIMIZED_BOTH);
        //this.setTitle(".: SISTEMA DE CONTROL DE PCs :.");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        contenedor = new javax.swing.JPanel();
        barraMenu = new javax.swing.JMenuBar();
        barraMantenimiento = new javax.swing.JMenu();
        mnuRegComputadora = new javax.swing.JMenuItem();
        mnuSalir = new javax.swing.JMenuItem();
        barraProcesos = new javax.swing.JMenu();
        mnuBuscarxSerie = new javax.swing.JMenuItem();
        barraReportes = new javax.swing.JMenu();
        mnuRepListadoGeneral = new javax.swing.JMenuItem();
        mnuRepCompuxMarca = new javax.swing.JMenuItem();
        barraAyuda = new javax.swing.JMenu();

        jMenu3.setText("jMenu3");

        jMenu5.setText("jMenu5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle(".: SISTEMA DE CONTROL DE PCs :.");
        setExtendedState(6);

        contenedor.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout contenedorLayout = new javax.swing.GroupLayout(contenedor);
        contenedor.setLayout(contenedorLayout);
        contenedorLayout.setHorizontalGroup(
            contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 476, Short.MAX_VALUE)
        );
        contenedorLayout.setVerticalGroup(
            contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 283, Short.MAX_VALUE)
        );

        barraMantenimiento.setText("Mantenimiento");

        mnuRegComputadora.setText("Registrar Computadora");
        mnuRegComputadora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuRegComputadoraActionPerformed(evt);
            }
        });
        barraMantenimiento.add(mnuRegComputadora);

        mnuSalir.setText("Salir");
        mnuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSalirActionPerformed(evt);
            }
        });
        barraMantenimiento.add(mnuSalir);

        barraMenu.add(barraMantenimiento);

        barraProcesos.setText("Procesos");

        mnuBuscarxSerie.setText("Buscar Computadora marca");
        mnuBuscarxSerie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuBuscarxSerieActionPerformed(evt);
            }
        });
        barraProcesos.add(mnuBuscarxSerie);

        barraMenu.add(barraProcesos);

        barraReportes.setText("Reportes");

        mnuRepListadoGeneral.setText("Listado General");
        mnuRepListadoGeneral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuRepListadoGeneralActionPerformed(evt);
            }
        });
        barraReportes.add(mnuRepListadoGeneral);

        mnuRepCompuxMarca.setText("Listado Computadoras x Marca");
        mnuRepCompuxMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuRepCompuxMarcaActionPerformed(evt);
            }
        });
        barraReportes.add(mnuRepCompuxMarca);

        barraMenu.add(barraReportes);

        barraAyuda.setText("Ayuda");
        barraMenu.add(barraAyuda);

        setJMenuBar(barraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mnuRegComputadoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuRegComputadoraActionPerformed
        // TODO add your handling code here:
        frmRegistrarPC  objForm = new frmRegistrarPC();
        
        contenedor.add(objForm);
        objForm.setVisible(true);
    }//GEN-LAST:event_mnuRegComputadoraActionPerformed

    private void mnuRepListadoGeneralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuRepListadoGeneralActionPerformed
        // TODO add your handling code here:
        frmListadoComputadoras  objForm = new frmListadoComputadoras();
        
        contenedor.add(objForm);
        objForm.setVisible(true);
    }//GEN-LAST:event_mnuRepListadoGeneralActionPerformed

    private void mnuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSalirActionPerformed
        // TODO add your handling code here:
        if(JOptionPane.showConfirmDialog(this, "¿Deseas salir del sistema?",
                                "Pregunta",JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION){
            this.dispose();
        }
    }//GEN-LAST:event_mnuSalirActionPerformed

    private void mnuRepCompuxMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuRepCompuxMarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuRepCompuxMarcaActionPerformed

    private void mnuBuscarxSerieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuBuscarxSerieActionPerformed
        // TODO add your handling code here:
        frmBuscarComputadora  objForm = new frmBuscarComputadora();
        
        contenedor.add(objForm);
        objForm.setVisible(true);
    }//GEN-LAST:event_mnuBuscarxSerieActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu barraAyuda;
    private javax.swing.JMenu barraMantenimiento;
    private javax.swing.JMenuBar barraMenu;
    private javax.swing.JMenu barraProcesos;
    private javax.swing.JMenu barraReportes;
    private javax.swing.JPanel contenedor;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuItem mnuBuscarxSerie;
    private javax.swing.JMenuItem mnuRegComputadora;
    private javax.swing.JMenuItem mnuRepCompuxMarca;
    private javax.swing.JMenuItem mnuRepListadoGeneral;
    private javax.swing.JMenuItem mnuSalir;
    // End of variables declaration//GEN-END:variables
}
