/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package capa_Presentacion;

import capa_Datos.ListaComputadoras;
import capa_Logica.Computadora;
import javax.swing.JOptionPane;

/**
 *
 * @author Sh
 */
public class frmRegistrarPC extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmRegistrarPCs
     */
    public frmRegistrarPC() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        eqtNumSerie = new javax.swing.JLabel();
        txtNumSerie = new javax.swing.JTextField();
        eqtMarca = new javax.swing.JLabel();
        cboMarca = new javax.swing.JComboBox<>();
        eqtColor = new javax.swing.JLabel();
        cboColor = new javax.swing.JComboBox<>();
        eqtAño = new javax.swing.JLabel();
        txtAño = new javax.swing.JTextField();
        eqtEstado = new javax.swing.JLabel();
        cboEstado = new javax.swing.JComboBox<>();
        btnRegistrar = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();

        setTitle("Registrar Computadora");

        eqtNumSerie.setText("Num serie:");

        eqtMarca.setText("Marca:");

        cboMarca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "HP", "Lenovo", "Dell", "Toshiba", "Asus" }));

        eqtColor.setText("Color:");

        cboColor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Blanco", "Negro", "Plomo", "Rojo", "Azul" }));

        eqtAño.setText("Año:");

        eqtEstado.setText("Estado:");

        cboEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Operativo", "Mantenimiento", "Inoperativo" }));

        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(eqtNumSerie)
                    .addComponent(eqtMarca)
                    .addComponent(eqtColor)
                    .addComponent(eqtAño)
                    .addComponent(eqtEstado))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtNumSerie, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                    .addComponent(txtAño)
                    .addComponent(cboEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(cboMarca, javax.swing.GroupLayout.Alignment.LEADING, 0, 130, Short.MAX_VALUE)
                        .addComponent(cboColor, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addComponent(btnRegistrar)
                .addGap(53, 53, 53)
                .addComponent(btnCerrar)
                .addGap(68, 68, 68))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eqtNumSerie)
                    .addComponent(txtNumSerie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eqtMarca)
                    .addComponent(cboMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eqtColor)
                    .addComponent(cboColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eqtAño)
                    .addComponent(txtAño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eqtEstado)
                    .addComponent(cboEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistrar)
                    .addComponent(btnCerrar))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        // TODO add your handling code here:
        try{
            Computadora objC = new Computadora();

            objC.setNumserie(txtNumSerie.getText());
            objC.setMarca(cboEstado.getSelectedItem().toString());
            objC.setColor(cboColor.getSelectedItem().toString());
            objC.setAño(Integer.parseInt(txtAño.getText()));
            objC.setEstado(cboEstado.getSelectedItem().toString());

            ListaComputadoras.agregar(objC);

            JOptionPane.showMessageDialog(this, "Computadora registrada", "MENSAJE DEL SISTEMA", JOptionPane.INFORMATION_MESSAGE);

            txtNumSerie.setText("");
            cboEstado.setSelectedIndex(0);
            cboColor.setSelectedIndex(0);
            txtAño.setText("");
            cboEstado.setSelectedIndex(0);

            txtNumSerie.requestFocus();//iniciar a registrar desde txtNumeSerie
        }catch(Exception error){
            JOptionPane.showMessageDialog(this, error.getMessage(), 
                    "ERROR DEL SISTEMA", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JComboBox<String> cboColor;
    private javax.swing.JComboBox<String> cboEstado;
    private javax.swing.JComboBox<String> cboMarca;
    private javax.swing.JLabel eqtAño;
    private javax.swing.JLabel eqtColor;
    private javax.swing.JLabel eqtEstado;
    private javax.swing.JLabel eqtMarca;
    private javax.swing.JLabel eqtNumSerie;
    private javax.swing.JTextField txtAño;
    private javax.swing.JTextField txtNumSerie;
    // End of variables declaration//GEN-END:variables
}
